### ISSUE TITLE
Fix macOS CI builds

### ISSUE THREAD

**Issue by sgoll** [HMIProject/open62541-sys#26]
## Description

The macOS build fails after the recent GitHub runner's [image update](https://github.com/actions/runner-images/pull/9940). For comparison, this is the exact same run before and after the update (`latest-dependencies` and `test` workflows, respectively):

- [2024-05-27](https://github.com/HMIProject/open62541-sys/actions/runs/9248740211/attempts/1) / [2024-05-03](https://github.com/HMIProject/open62541-sys/actions/runs/8942062781/attempts/1)
- [2024-05-30](https://github.com/HMIProject/open62541-sys/actions/runs/9248740211/attempts/2) / [2024-05-30](https://github.com/HMIProject/open62541-sys/actions/runs/8942062781/attempts/2)

The relevant error during compilation/build is this:

> /Applications/Xcode_15.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include/inttypes.h:21:15: fatal error: 'inttypes.h' file not found

We need to check whether this is something that we have to work around or that needs to be fixed upstream (GitHub or open62541).

**Comment by uklotzde** [comment]
This will affect all downstream projects with macOS runners.

Incomplete `#include` directives frequently cause issue when upgrading C/C++ compiler toolchains and dependencies. Broken by design.
